import Footer from "@/pages/rootapp/Footer"
import "./globals.css";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};


export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body>
        {children}
        <Footer />
        </body>
        </html>
    );
}
