export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

interface LayoutProps {
  children: React.ReactNode;
  layoutType: 'layout1' | 'layout2';
}

const Layout: React.FC<LayoutProps> = ({ children, layoutType }) => {
  return (
    <>
      <div className="Gradient">
        {children}
        </div>
    </>
  )
}
export default Layout;